CONFIG = {
    "main_window_title" : "样机出样测试工具",
    "main_window_geometry": "800x600+600+300",
    "test_modules" : "测试项目",
    "test_states" : ["NA", "OK", "NG","NONE"],
    "load_frame_name" : "设置",
    "load_data_button_name" : "加载数据",
    "save_data_button_name" : "保存数据",
    "creat_report_button_name" : "生成样机测试报告",
    "creat_report_entry_name" : "生成测试报告路径:",
    "open_dir_button_name" : "打开目录",
    "cover_report_entry_name" : "覆盖测试报告路径:",
    "open_file_button_name" : "打开文件",
    "basic_frame_name" : "基本信息",
    "excel_title_list" : ["样机/版本外发测试(业务人员：   )","设备型号","测试时间","测试人员","样机数量","电源","样机/版本确认"],
    "salesman_list" : ['庄思峰','张佰鹏','陈江','何万海','李杨','刑鹏','郭瑞丽','陈小兰','翁佳坤','刘芳芳','熊韵','游佳佳','曾玉春'],
    "usb_comm_button_name" : "尝试获取(USB获取)",
    "test_person_list" : ['测试组','张明钰','王琪','刘挺挺','黄明委'],
    "power_list" : ['24V','12V','9V'],
}